# Generated by Django 5.2.1 on 2025-08-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
